window.translations = window.translations || {};
window.translations.en = {
    "nav-destinations": "Destinations",
    "nav-hotels": "Hotels",
    "nav-flights": "Flights",
    "nav-bookings": "Bookings",
    "ui-login": "Login",
    "ui-signUp": "Sign up",
    "hero-subtitle": "best destinations around the world",
    "hero-title": "Travel, <span class=highlighted-enjoy>enjoy</span> and live a new and full life",
    "hero-descr": "Built Wicket longer admire do barton vanity itself do in it. Preferred to sportsmen it engrossed listening. Park gate sell they west hard for the.",
    "hero-findMore": "Find out more",
    "cat-text": "CATEGORY",
    "cat-adv": "We Offer Best Services",
    "cat-catTitleFirst": "Calculated Weather",
    "cat-catDescFirst": "Built Wicket longer admire do barton vanity itself do in it.",
    "cat-catTitleSecond": "Best Flights",
    "cat-catDescSecond": "Engrossed listening. Park gate sell they west hard for the.",
    "cat-catTitleThird": "Local Events",
    "cat-catDescThird": "Barton vanity itself do in it. Preferd to men it engrossed listening.",
    "cat-catTitleFourth": "Customization",
    "cat-catDescFourth": "We deliver outsourced aviation services for military customers",
    "selling-title": "Top Selling",
    "selling-dest": "Top Destinations",
    "selling-cardTitleFirst": "Rome, Italy",
    "selling-cardPriceFirst": "$5.42k",
    "selling-carTripFirst": "<img src=\"img/top-selling-card-arrow.png\" alt=\"\" aria-hidden=\"true\" />10 Days Trip",
    "selling-cardTitleSecond": "London, UK",
    "selling-cardPriceSecond": "$4.2k",
    "selling-carTripSecond": "<img src=\"img/top-selling-card-arrow.png\" alt=\"\" aria-hidden=\"true\" />12 Days Trip",
    "selling-cardTitleThird": "Full Europe",
    "selling-cardPriceThird": "$15k",
    "selling-carTripThird": "<img src=\"img/top-selling-card-arrow.png\" alt=\"\" aria-hidden=\"true\" />28 Days Trip",
    "booking-title": "Easy and Fast",
    "booking-action": "Book Your Next Trip In 3 Easy Steps",
    "booking-stepTitleFirst": "Choose Destination <br\/\> <span class=\"booking__step-desc\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Urna, tortor tempus.</span>",
    "booking-stepTitleSecond": "Make Payment <br\/\> <span class=\"booking__step-desc\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Urna, tortor tempus.</span>",
    "booking-stepTitleThird": "Reach Airport on Selected Date <br\/\> <span class=\"booking__step-desc\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Urna, tortor tempus.</span>",
    "booking-cardTitle": "Trip To Greece",
    "booking-cardDetails": "14-29 June | by Robbin jo",
    "booking-cardFollowers": "24 people going",
    "tooltip-title": "Ongoing",
    "tooltip-desc": "Trip To Rome",
    "tooltip-progressText": "completed",
    "testnls-title": "TESTIMONIALS",
    "testnls-about": "What People Say About Us.",
    "testnls-quoteActive": "“On the Windows talking painted pasture yet its express parties use. Sure last upon he same as knew next. Of believed or diverted no.”",
    "testnls-authorActive": "Mike Taylor",
    "testnls-locActive": "Lahore, Pakistan",
    "testnls-quote": "“On the Windows talking painted pasture yet its express parties use.",
    "testnls-author": "Chris Thomas",
    "testnls-loc": "CEO of Red Button",
    "subscribe-title": "Subscribe to get information, latest news and other interesting offers about Jadoo",
    "susbscribe-buttonText": "Subscribe",
    "footer-brandTitle": "Jadoo.",
    "footer-brandSlogan": "Book your trip in minute, get full Control for much longer.",
    "ftr-companyTitle": "Company",
    "ftr-companyAbout": "About",
    "ftr-companyCareers": "Careers",
    "ftr-companyMob": "Mobile",
    "ftr-contactTitle": "Contact",
    "ftr-contactHelp": "Help/FAQ",
    "ftr-contactPress": "Press",
    "ftr-contactAffil": "Affilates",
    "ftr-moreTitle": "More",
    "ftr-moreAirFees": "Airlinesfees",
    "ftr-moreAirline": "Airline",
    "ftr-moreTips": "Low fare tips",
    "ftr-socialText": "Discover our app",
    "ftr-rightsText": "All rights reserved@jadoo.co",
    //placeholders
    "subscribe-placeholder": "Your email",
    //aria-labels
    "header-main-page": "Main Site Page",
    "header-site-nav": "Main Site Navigation",
    "header-ui": "User interface",
    "header-lang": "Site language",
    "header-mainPic": "Hero section main picture",
    "progress-done": "Progress done",
    //site title
    "page-title": "Travel Page"
};