window.translations = window.translations || {};
window.translations.ru = {
    "nav-destinations": "Направления",
    "nav-hotels": "Отели",
    "nav-flights": "Рейсы",
    "nav-bookings": "Бронирование",
    "ui-login": "Логин",
    "ui-signUp": "Регистрация",
    "hero-subtitle": "лучшие направления по всему миру",
    "hero-title": "Путешествуй, <span class=highlighted-enjoy>наслаждайся</span> и живи новой жизнью на полную",
    "hero-descr": "Билт Викет восхищается этими путешествиями делая их лично. Преподчитает их больше, чем спорту и слушаниям рассказов",
    "hero-findMore": "Узнать больше",
    "cat-text": "КАТЕГОРИИ",
    "cat-adv": "Мы Предлагаем Лучшие Сервисы",
    "cat-catTitleFirst": "Прогнозируем погоду",
    "cat-catDescFirst": "Билт Викет восхищается этими путешествиями делая их лично",
    "cat-catTitleSecond": "Лучшие рейсы",
    "cat-catDescSecond": "Engrossed listening. Park gate sell they west hard for the.",
    "cat-catTitleThird": "Местные праздники",
    "cat-catDescThird": "Barton vanity itself do in it. Preferd to men it engrossed listening.",
    "cat-catTitleFourth": "Гибкость",
    "cat-catDescFourth": "We deliver outsourced aviation services for military customers",
    "selling-title": "Лучшие продажи",
    "selling-dest": "Лучшие направления",
    "selling-cardTitleFirst": "Рим, Италия",
    "selling-cardPriceFirst": "$5.42к",
    "selling-carTripFirst": "<img src=\"img/top-selling-card-arrow.png\" alt=\"\" aria-hidden=\"true\" />10 Дневное Путешествие",
    "selling-cardTitleSecond": "Лондон, Британия",
    "selling-cardPriceSecond": "$4.2к",
    "selling-carTripSecond": "<img src=\"img/top-selling-card-arrow.png\" alt=\"\" aria-hidden=\"true\" />12 Дневное Путешествие",
    "selling-cardTitleThird": "Вся Европа",
    "selling-cardPriceThird": "$15к",
    "selling-carTripThird": "<img src=\"img/top-selling-card-arrow.png\" alt=\"\" aria-hidden=\"true\" />28 Дневное Путешествие",
    "booking-title": "Легко и Быстро",
    "booking-action": "Забронируйте Ваше Следующее Путешествие За 3 Лёгких Шага",
    "booking-stepTitleFirst": "Выберите направление <br\/\> <span class=\"booking__step-desc\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Urna, tortor tempus.</span>",
    "booking-stepTitleSecond": "Оплатите <br\/\> <span class=\"booking__step-desc\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Urna, tortor tempus.</span>",
    "booking-stepTitleThird": "Прибудьте в аэропорт в выбранную дату <br\/\> <span class=\"booking__step-desc\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Urna, tortor tempus.</span>",
    "booking-cardTitle": "Путешествие в Грецию",
    "booking-cardDetails": "14-29 Июня | с Роббин джо",
    "booking-cardFollowers": "24 подписчика",
    "tooltip-title": "Открыто",
    "tooltip-desc": "Путешествие В Рим",
    "tooltip-progressText": "выполнено",
    "testnls-title": "ОТЗЫВЫ",
    "testnls-about": "Что Говорят О Нас Люди.",
    "testnls-quoteActive": "“На окнах, говорящих о нарисованном пастбище, всё ещё используются его выразительные стороны. Уверен, что последний раз он был таким же, как и знал следующий. Верили или отвлекались, нет.”",
    "testnls-authorActive": "Майк Тайлор",
    "testnls-locActive": "Лаор, Пакистан",
    "testnls-quote": "“На окнах, говорящих о нарисованном пастбище, всё ещё используются его выразительные стороны.",
    "testnls-author": "Крис Томас",
    "testnls-loc": "Руководитель Ред Баттон",
    "subscribe-title": "Подпишись чтобы получать информацию, последние новости и интересные предложения о Jadoo",
    "susbscribe-buttonText": "Подписаться",
    "footer-brandTitle": "Jadoo.",
    "footer-brandSlogan": "Забронируй путешествие за минуту, получи Управление на гораздо дольше",
    "ftr-companyTitle": "Компания",
    "ftr-companyAbout": "О нас",
    "ftr-companyCareers": "Карьера",
    "ftr-companyMob": "Телефоны",
    "ftr-contactTitle": "Контакт",
    "ftr-contactHelp": "Помощь/FAQ",
    "ftr-contactPress": "Пресса",
    "ftr-contactAffil": "Филиалы",
    "ftr-moreTitle": "Больше",
    "ftr-moreAirFees": "Авиасборы",
    "ftr-moreAirline": "Рейсы",
    "ftr-moreTips": "О низких тарифах",
    "ftr-socialText": "Установите наше приложение",
    "ftr-rightsText": "Все права защищены reserved@jadoo.co",
    //placeholders
    "subscribe-placeholder": "Ваш email",
    //aria-labels
    "header-main-page": "Главная страница сайта",
    "header-site-nav": "Главная страница навигация",
    "header-ui": "Пользовательский интерфейс",
    "header-lang": "Язык сайта",
    "header-mainPic": "Хиро секция главное изображение",
    "progress-done": "Выполнено",
    //site title
    "page-title": "Страница путешествий"
};